"""
Tacacs+ 管理与日志查询。
"""
import re
import json
import socket
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query

from app.config import settings
from app.models import User
from app.routers.auth import get_current_active_user
from app.utils import notification_manager

router = APIRouter()

TACACS_DATA_DIR = Path("/app/data/tacacs")
TACACS_CONFIG_FILE = TACACS_DATA_DIR / "tac_plus.cfg"
TACACS_LOG_FILE = TACACS_DATA_DIR / "logs" / "tacacs.log"
TACACS_SETTINGS_FILE = TACACS_DATA_DIR / "settings.json"
TACACS_CONTAINER_NAME = "nm-tacacs"
DOCKER_SOCKET = "/var/run/docker.sock"

LOG_PATTERN = re.compile(r"(\w+\s+\d+\s+\d+:\d+:\d+)\s+(\d+\.\d+\.\d+\.\d+)\s+(\w+)\s+(\S+)\s+(\S+).*?cmd=(.*)")
MONTH_MAP = {
    "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6,
    "Jul": 7, "Aug": 8, "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12,
}


def _ensure_data_dir() -> None:
    (TACACS_DATA_DIR / "logs").mkdir(parents=True, exist_ok=True)


def _ensure_config_file(settings_payload: Optional[Dict[str, Any]] = None) -> None:
    _ensure_data_dir()
    if TACACS_CONFIG_FILE.exists() and TACACS_CONFIG_FILE.is_dir():
        TACACS_CONFIG_FILE.rmdir()
    if not TACACS_CONFIG_FILE.exists():
        TACACS_CONFIG_FILE.write_text(_render_config(settings_payload or _load_settings()), encoding="utf-8")


def _detect_notification_type(webhook_url: str) -> str:
    url = (webhook_url or "").strip().lower()
    if "work.weixin.qq.com" in url or "qyapi.weixin.qq.com" in url:
        return "wechat"
    if "oapi.dingtalk.com" in url or "api.dingtalk.com" in url:
        return "dingtalk"
    if "open.feishu.cn" in url or "open.larksuite.com" in url:
        return "feishu"
    return "webhook"


def _parse_log_time(raw_time: str) -> Optional[str]:
    try:
        month_text, day, time_text = raw_time.split()
        hour, minute, second = [int(item) for item in time_text.split(":")]
        parsed = datetime(datetime.now().year, MONTH_MAP[month_text], int(day), hour, minute, second)
        return (parsed + timedelta(hours=8)).strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        return None


def _extract_command(raw_command: str) -> str:
    text = (raw_command or "").strip()
    if not text:
        return ""
    marker_match = re.search(r"\s+(cmd-arg|err_msg|start_time)=", text)
    command = text[:marker_match.start()].strip() if marker_match else text
    rest = text[marker_match.start():] if marker_match else ""
    arg_match = re.search(
        r"\bcmd-arg=(.*?)(?=\s+(?:err_msg|start_time)=|$)",
        rest,
    )
    cmd_arg = arg_match.group(1).strip() if arg_match else ""
    if cmd_arg:
        return f"{command} {cmd_arg}".strip()
    return command


def _render_command_block(command: Dict[str, Any]) -> str:
    name = str(command.get("name") or "").strip()
    if not name:
        return ""
    permits = command.get("permit") or []
    denies = command.get("deny") or []
    lines = [f"    cmd = {name} {{"]
    for pattern in permits:
        lines.append(f"        permit {pattern}")
    for pattern in denies:
        lines.append(f"        deny {pattern}")
    lines.append("    }")
    return "\n".join(lines)


def _render_config(payload: Dict[str, Any]) -> str:
    key = str(payload.get("key") or "testing123").replace('"', '\\"')
    accounting_file = str(payload.get("accounting_file") or "/var/log/tacacs+/tacacs.log")
    roles = payload.get("roles") or []
    users = payload.get("users") or []

    lines = [
        "# Generated by 并行网络运营平台",
        f'key = "{key}"',
        "",
        f"accounting file = {accounting_file}",
        "",
    ]

    for role in roles:
        name = str(role.get("name") or "").strip()
        if not name:
            continue
        priv_lvl = int(role.get("priv_lvl") or 1)
        default_service = "permit" if role.get("default_permit", True) else "deny"
        lines.extend([
            f"group = {name} {{",
            f"    default service = {default_service}",
            "    service = exec {",
            f"        priv-lvl = {priv_lvl}",
            "    }",
            "    service = shell {",
            f"        priv-lvl = {priv_lvl}",
            "    }",
        ])
        for command in role.get("commands") or []:
            block = _render_command_block(command)
            if block:
                lines.append(block)
        lines.extend(["}", ""])

    for account in users:
        username = str(account.get("username") or "").strip()
        password = str(account.get("password") or "").replace('"', '\\"')
        role = str(account.get("role") or "").strip()
        if not username or not password or not role:
            continue
        lines.extend([
            f"user = {username} {{",
            f'    login = cleartext "{password}"',
            f'    pap = cleartext "{password}"',
            f"    member = {role}",
            "}",
            "",
        ])

    return "\n".join(lines).rstrip() + "\n"


def _default_settings() -> Dict[str, Any]:
    default_channels = []
    if settings.TACACS_WEBHOOK_URL.strip():
        default_channels.append({"type": "dingtalk", "webhook": settings.TACACS_WEBHOOK_URL.strip()})
    return {
        "key": "para@2026",
        "accounting_file": "/var/log/tacacs+/tacacs.log",
        "roles": [
            {
                "name": "network_admin",
                "priv_lvl": 15,
                "default_permit": True,
                "commands": [
                    {"name": "show", "permit": [".*"], "deny": []},
                    {"name": "display", "permit": [".*"], "deny": []},
                    {"name": "system-view", "permit": [".*"], "deny": []},
                ],
            }
        ],
        "users": [
            {"username": "lvfz", "password": "234", "role": "network_admin"},
        ],
        "notification_channels": default_channels,
    }


def _load_settings() -> Dict[str, Any]:
    _ensure_data_dir()
    if TACACS_SETTINGS_FILE.exists():
        try:
            loaded = json.loads(TACACS_SETTINGS_FILE.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                return {**_default_settings(), **loaded}
        except Exception:
            pass
    return _default_settings()


def _save_settings(payload: Dict[str, Any]) -> None:
    _ensure_data_dir()
    TACACS_SETTINGS_FILE.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def _restart_docker_container(container_name: str) -> None:
    if not Path(DOCKER_SOCKET).exists():
        raise HTTPException(status_code=500, detail="API容器未挂载Docker Socket，无法重启Tacacs容器")

    request = (
        f"POST /containers/{container_name}/restart?t=10 HTTP/1.1\r\n"
        "Host: docker\r\n"
        "Content-Length: 0\r\n"
        "Connection: close\r\n\r\n"
    )
    try:
        with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as client:
            client.settimeout(15)
            client.connect(DOCKER_SOCKET)
            client.sendall(request.encode("utf-8"))
            response = client.recv(4096).decode("utf-8", errors="ignore")
    except OSError as exc:
        raise HTTPException(status_code=500, detail=f"重启Tacacs容器失败：{exc}") from exc

    status_line = response.splitlines()[0] if response else ""
    if " 204 " in status_line or " 200 " in status_line:
        return
    if " 404 " in status_line:
        raise HTTPException(status_code=404, detail=f"未找到Tacacs容器：{container_name}")
    raise HTTPException(status_code=500, detail=f"Docker重启Tacacs容器失败：{status_line or '无响应'}")


@router.get("/config", response_model=dict)
async def get_tacacs_config(current_user: User = Depends(get_current_active_user)):
    _ensure_data_dir()
    settings = _load_settings()
    _ensure_config_file(settings)
    content = TACACS_CONFIG_FILE.read_text(encoding="utf-8")
    return {
        "path": str(TACACS_CONFIG_FILE),
        "exists": TACACS_CONFIG_FILE.exists(),
        "content": content,
        "settings": settings,
    }


@router.post("/config", response_model=dict)
async def save_tacacs_config(
    payload: Dict[str, Any],
    current_user: User = Depends(get_current_active_user),
):
    _ensure_data_dir()
    settings = {**_default_settings(), **payload}
    content = _render_config(settings)
    _save_settings(settings)
    if TACACS_CONFIG_FILE.exists() and TACACS_CONFIG_FILE.is_dir():
        TACACS_CONFIG_FILE.rmdir()
    TACACS_CONFIG_FILE.write_text(content, encoding="utf-8")
    return {"path": str(TACACS_CONFIG_FILE), "content": content, "settings": settings}


@router.post("/notifications", response_model=dict)
async def save_tacacs_notifications(
    payload: Dict[str, Any],
    current_user: User = Depends(get_current_active_user),
):
    raw_channels = payload.get("notification_channels") or []
    if not isinstance(raw_channels, list):
        raise HTTPException(status_code=400, detail="机器人通知配置格式不正确")

    channels = []
    for channel in raw_channels:
        webhook = str((channel or {}).get("webhook") or (channel or {}).get("url") or "").strip()
        if not webhook:
            continue
        channels.append({
            "type": _detect_notification_type(webhook),
            "webhook": webhook,
        })

    settings = _load_settings()
    settings["notification_channels"] = channels
    _save_settings(settings)
    return {
        "message": "机器人通知已保存",
        "settings": settings,
    }


@router.post("/restart", response_model=dict)
async def restart_tacacs_container(current_user: User = Depends(get_current_active_user)):
    _restart_docker_container(TACACS_CONTAINER_NAME)
    return {"message": "Tacacs容器重启已触发", "container": TACACS_CONTAINER_NAME}


@router.post("/test-notification", response_model=dict)
async def test_tacacs_notification(
    payload: Dict[str, Any],
    current_user: User = Depends(get_current_active_user),
):
    webhook_url = str(payload.get("url") or payload.get("webhook") or "").strip()
    if not webhook_url:
        raise HTTPException(status_code=400, detail="Webhook 地址不能为空")

    channel_type = _detect_notification_type(webhook_url)
    config = {"url": webhook_url} if channel_type == "webhook" else {"webhook": webhook_url}
    now_text = (datetime.utcnow() + timedelta(hours=8)).strftime("%Y-%m-%d %H:%M:%S")
    success = await notification_manager.send_notification(
        channel_type,
        config,
        "Tacacs命令操作通知",
        (
            "操作设备: 10.242.2.26\n\n"
            "操作人员: test\n\n"
            f"操作时间: {now_text}\n\n"
            "操作命令:\n· display version\n· display ip interface brief"
        ),
        {
            "severity": "TACACS",
            "notification_type": "tacacs",
            "title": "Tacacs命令操作通知",
            "headline": "Tacacs",
            "summary": "test @ 10.242.2.26",
            "subtitle": now_text,
            "rows": [
                {"label": "操作设备", "value": "10.242.2.26"},
                {"label": "操作人员", "value": "test"},
                {"label": "操作时间", "value": now_text},
                {"label": "操作命令", "value": "\n· display version\n· display ip interface brief"},
            ],
        },
    )

    if not success:
        detail = notification_manager.last_error_message or f"{channel_type} 测试消息发送失败，请检查 webhook 地址或机器人配置"
        raise HTTPException(status_code=400, detail=detail)

    return {
        "success": True,
        "channel_type": channel_type,
        "message": f"{channel_type} 测试消息发送成功",
    }


@router.get("/logs", response_model=dict)
async def list_tacacs_logs(
    current_user: User = Depends(get_current_active_user),
    skip: int = Query(0, ge=0),
    limit: int = Query(200, ge=1, le=1000),
    search: Optional[str] = None,
    start_time: Optional[str] = None,
    end_time: Optional[str] = None,
    device_ip: Optional[str] = None,
    username: Optional[str] = None,
    command: Optional[str] = None,
):
    _ensure_data_dir()
    if not TACACS_LOG_FILE.exists():
        return {"total": 0, "items": [], "path": str(TACACS_LOG_FILE)}

    keyword = (search or "").strip().lower()
    start_value = (start_time or "").strip()
    end_value = (end_time or "").strip()
    device_value = (device_ip or "").strip().lower()
    username_value = (username or "").strip().lower()
    command_value = (command or "").strip().lower()
    total = 0
    items: List[Dict[str, Any]] = []
    for line in reversed(TACACS_LOG_FILE.read_text(encoding="utf-8", errors="ignore").splitlines()):
        if "cmd=" not in line:
            continue
        match = LOG_PATTERN.search(line)
        if not match:
            continue
        command_text = _extract_command(match.group(6))
        if not command_text or command_text in {"startup"}:
            continue
        item = {
            "time": _parse_log_time(match.group(1)) or match.group(1),
            "device_ip": match.group(2),
            "username": match.group(3),
            "tty": match.group(4),
            "client_ip": match.group(5),
            "command": command_text,
            "raw": line,
        }
        item_time = str(item["time"])
        if start_value and item_time < start_value:
            continue
        if end_value and item_time > end_value:
            continue
        if device_value and device_value not in item["device_ip"].lower():
            continue
        if username_value and username_value not in item["username"].lower():
            continue
        if command_value and command_value not in item["command"].lower():
            continue
        if keyword and keyword not in " ".join(str(value).lower() for value in item.values()):
            continue
        total += 1
        if total <= skip:
            continue
        if len(items) < limit:
            items.append(item)
    return {"total": total, "items": items, "path": str(TACACS_LOG_FILE)}
