apiVersion: 1

datasources:
  - name: NetworkMonitor-InfluxDB
    uid: network-monitor-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: network-monitor
      defaultBucket: network_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}

  - name: NetworkMonitor-PostgreSQL
    uid: network-monitor-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: grafana_reader
    database: network_monitor
    editable: false
    jsonData:
      database: network_monitor
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
