from celery import Celery
from app.config import settings
from app.tasks.celerybeat_schedule import beat_schedule

# 创建Celery应用
celery_app = Celery(
    "network_monitor",
    broker=settings.CELERY_BROKER_URL,
    backend=settings.CELERY_RESULT_BACKEND,
    include=[
        "app.tasks.snmp_tasks",
        "app.tasks.alert_tasks",
        "app.tasks.notification_tasks",
        "app.tasks.resource_tasks",
        "app.tasks.tacacs_tasks",
        "app.tasks.system_tasks",
        "app.tasks.config_backup_tasks",
        "app.tasks.menu_cache_tasks",
        "app.tasks.quality_tasks",
    ]
)

# Celery配置
celery_app.conf.update(
    task_serializer="json",
    accept_content=["json"],
    result_serializer="json",
    timezone="Asia/Shanghai",
    enable_utc=True,
    task_track_started=True,
    task_time_limit=300,
    task_default_queue="celery",
    task_routes={
        "app.tasks.snmp_tasks.collect_all_snmp": {"queue": "snmp_realtime"},
        "app.tasks.snmp_tasks.collect_snmp_for_device": {"queue": "snmp_realtime"},
        "app.tasks.snmp_tasks.collect_all_snmp_interface_realtime": {"queue": "snmp_interface_realtime"},
        "app.tasks.snmp_tasks.collect_h3c_vlan_statistics": {"queue": "snmp_interface_realtime"},
        "app.tasks.snmp_tasks.collect_h3c_s9867_roce_interface_health": {"queue": "snmp_interface_realtime"},
        "app.tasks.snmp_tasks.collect_circuit_interface_realtime": {"queue": "snmp_circuit_realtime"},
        "app.tasks.snmp_tasks.collect_incident_interface_realtime": {"queue": "snmp_circuit_realtime"},
        "app.tasks.snmp_tasks.prewarm_device_detail_caches": {"queue": "system"},
        "app.tasks.snmp_tasks.collect_forwarding_for_device": {"queue": "system"},
        "app.tasks.snmp_tasks.prewarm_forwarding_caches": {"queue": "system"},
        "app.tasks.snmp_tasks.ensure_qos_discard_rules": {"queue": "system"},
        "app.tasks.snmp_tasks.ensure_h3c_s9867_roce_rules": {"queue": "system"},
        "app.tasks.snmp_tasks.ensure_up_interface_crc_rules": {"queue": "system"},
        "app.tasks.snmp_tasks.ensure_asternos_up_interface_quality_rules": {"queue": "system"},
        "app.tasks.alert_tasks.check_fast_alerts": {"queue": "alerts_fast"},
        "app.tasks.alert_tasks.check_fast_state_alerts": {"queue": "alerts_fast"},
        "app.tasks.alert_tasks.check_fast_crc_alerts": {"queue": "alerts_fast"},
        "app.tasks.alert_tasks.check_fast_error_alerts": {"queue": "alerts_fast"},
        "app.tasks.alert_tasks.check_fast_discard_alerts": {"queue": "alerts_fast"},
        "app.tasks.alert_tasks.resolve_interface_alerts_quick": {"queue": "alerts_health"},
        "app.tasks.snmp_tasks.collect_all_asternos_interface_realtime": {"queue": "asternos_realtime"},
        "app.tasks.snmp_tasks.collect_all_asternos_exporter": {"queue": "asternos"},
        "app.tasks.snmp_tasks.collect_asternos_for_device": {"queue": "asternos"},
        "app.tasks.snmp_tasks.collect_asternos_software_patches": {"queue": "system"},
        "app.tasks.alert_tasks.check_reachability_alerts": {"queue": "alerts_health"},
        "app.tasks.alert_tasks.check_protocol_alerts": {"queue": "alerts_protocol"},
        "app.tasks.alert_tasks.reconcile_hillstone_bfd_trap_alerts": {"queue": "alerts_protocol"},
        "app.tasks.alert_tasks.reconcile_hillstone_bgp_trap_alerts": {"queue": "alerts_protocol"},
        "app.tasks.alert_tasks.check_device_health_alerts": {"queue": "alerts_health"},
        "app.tasks.alert_tasks.check_optical_alerts": {"queue": "alerts_general"},
        "app.tasks.alert_tasks.reconcile_syslog_optical_power_alerts": {"queue": "alerts_health"},
        "app.tasks.alert_tasks.check_alerts": {"queue": "alerts_general"},
        "app.tasks.alert_tasks.prewarm_alert_rule_status_cache": {"queue": "alerts_prewarm"},
        "app.tasks.alert_tasks.prewarm_alert_silence_match_counts": {"queue": "alerts_prewarm"},
        "app.tasks.alert_tasks.resolve_stale_alerts": {"queue": "alerts_general"},
        "app.tasks.alert_tasks._send_alert_notification": {"queue": "notification"},
        "app.tasks.alert_tasks._send_alert_event_notification": {"queue": "notification"},
        "app.tasks.notification_tasks.*": {"queue": "notification"},
        "app.tasks.tacacs_tasks.process_tacacs_command_logs": {"queue": "tacacs"},
        "app.tasks.resource_tasks.collect_circuit_usage_hourly": {"queue": "resource"},
        "app.tasks.system_tasks.check_influxdb_storage_health": {"queue": "system"},
        "app.tasks.system_tasks.collect_server_resources": {"queue": "system"},
        "app.tasks.menu_cache_tasks.prewarm_fast_menu_caches": {"queue": "system"},
        "app.tasks.menu_cache_tasks.prewarm_device_overview_cache": {"queue": "system"},
        "app.tasks.menu_cache_tasks.prewarm_traffic_query_cache": {"queue": "system"},
        "app.tasks.quality_tasks.collect_quality_probes": {"queue": "system"},
        "app.tasks.quality_tasks.collect_quality_fast_outages": {"queue": "system"},
        "app.tasks.quality_tasks.collect_quality_mtr_paths": {"queue": "system"},
        "app.tasks.config_backup_tasks.run_config_backup": {"queue": "config_backup"},
        "app.tasks.config_backup_tasks.run_scheduled_config_backup": {"queue": "config_backup"},
    },
    worker_prefetch_multiplier=1,
    worker_max_tasks_per_child=1000,
    beat_schedule=beat_schedule,  # 定时任务调度配置
)

__all__ = ["celery_app"]
